// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.buildulator.model;

import net.triptech.buildulator.model.EnergySource;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EnergySource_Roo_Configurable {
    
    declare @type: EnergySource: @Configurable;
    
}
