// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.buildulator.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.triptech.buildulator.model.EnergySource;
import net.triptech.buildulator.model.EnergySourceDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect EnergySourceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EnergySourceDataOnDemand: @Component;
    
    private Random EnergySourceDataOnDemand.rnd = new SecureRandom();
    
    private List<EnergySource> EnergySourceDataOnDemand.data;
    
    public EnergySource EnergySourceDataOnDemand.getNewTransientEnergySource(int index) {
        EnergySource obj = new EnergySource();
        setCarbonPerUnit(obj, index);
        setEnergyPerUnit(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void EnergySourceDataOnDemand.setCarbonPerUnit(EnergySource obj, int index) {
        double carbonPerUnit = new Integer(index).doubleValue();
        obj.setCarbonPerUnit(carbonPerUnit);
    }
    
    public void EnergySourceDataOnDemand.setEnergyPerUnit(EnergySource obj, int index) {
        double energyPerUnit = new Integer(index).doubleValue();
        obj.setEnergyPerUnit(energyPerUnit);
    }
    
    public void EnergySourceDataOnDemand.setName(EnergySource obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public EnergySource EnergySourceDataOnDemand.getSpecificEnergySource(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EnergySource obj = data.get(index);
        Long id = obj.getId();
        return EnergySource.findEnergySource(id);
    }
    
    public EnergySource EnergySourceDataOnDemand.getRandomEnergySource() {
        init();
        EnergySource obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return EnergySource.findEnergySource(id);
    }
    
    public boolean EnergySourceDataOnDemand.modifyEnergySource(EnergySource obj) {
        return false;
    }
    
    public void EnergySourceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = EnergySource.findEnergySourceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EnergySource' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EnergySource>();
        for (int i = 0; i < 10; i++) {
            EnergySource obj = getNewTransientEnergySource(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
