// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.buildulator.model;

import java.util.List;
import net.triptech.buildulator.model.Material;
import net.triptech.buildulator.model.MaterialDataOnDemand;
import net.triptech.buildulator.model.MaterialIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MaterialIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MaterialIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MaterialIntegrationTest: @Transactional;
    
    @Autowired
    private MaterialDataOnDemand MaterialIntegrationTest.dod;
    
    @Test
    public void MaterialIntegrationTest.testCountMaterials() {
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", dod.getRandomMaterial());
        long count = Material.countMaterials();
        Assert.assertTrue("Counter for 'Material' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MaterialIntegrationTest.testFindMaterial() {
        Material obj = dod.getRandomMaterial();
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Material' failed to provide an identifier", id);
        obj = Material.findMaterial(id);
        Assert.assertNotNull("Find method for 'Material' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Material' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MaterialIntegrationTest.testFindAllMaterials() {
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", dod.getRandomMaterial());
        long count = Material.countMaterials();
        Assert.assertTrue("Too expensive to perform a find all test for 'Material', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Material> result = Material.findAllMaterials();
        Assert.assertNotNull("Find all method for 'Material' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Material' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MaterialIntegrationTest.testFindMaterialEntries() {
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", dod.getRandomMaterial());
        long count = Material.countMaterials();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Material> result = Material.findMaterialEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Material' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Material' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MaterialIntegrationTest.testFlush() {
        Material obj = dod.getRandomMaterial();
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Material' failed to provide an identifier", id);
        obj = Material.findMaterial(id);
        Assert.assertNotNull("Find method for 'Material' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMaterial(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Material' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MaterialIntegrationTest.testMergeUpdate() {
        Material obj = dod.getRandomMaterial();
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Material' failed to provide an identifier", id);
        obj = Material.findMaterial(id);
        boolean modified =  dod.modifyMaterial(obj);
        Integer currentVersion = obj.getVersion();
        Material merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Material' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MaterialIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", dod.getRandomMaterial());
        Material obj = dod.getNewTransientMaterial(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Material' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Material' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Material' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MaterialIntegrationTest.testRemove() {
        Material obj = dod.getRandomMaterial();
        Assert.assertNotNull("Data on demand for 'Material' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Material' failed to provide an identifier", id);
        obj = Material.findMaterial(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Material' with identifier '" + id + "'", Material.findMaterial(id));
    }
    
}
